### ISSUE TITLE
Minor issue: Game Crashes when moving pawn to the 8 rank

### ISSUE THREAD

**Issue by sashabjorkman** [INDA23PlusPlus/emilaa-chess#3]
Relevant stack trace:
```
thread 'main' panicked at 'attempt to subtract with overflow', C:\Users\ab3mi\.cargo\git\checkouts\emilaa-chess-cfcf17888f64ed4e\1aa0496\src\lib.rs:345:38
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:117
   3: chess::ChessBoard::check_pawn_move
             at C:\Users\ab3mi\.cargo\git\checkouts\emilaa-chess-cfcf17888f64ed4e\1aa0496\src\lib.rs:345
   4: chess::ChessBoard::is_move_legal
             at C:\Users\ab3mi\.cargo\git\checkouts\emilaa-chess-cfcf17888f64ed4e\1aa0496\src\lib.rs:296
   5: chess::ChessBoard::move_by_index
             at C:\Users\ab3mi\.cargo\git\checkouts\emilaa-chess-cfcf17888f64ed4e\1aa0496\src\lib.rs:251
```
Probably doesn't matter as I assume pawn-promotion isn't implemented.
Warmest regards, Alexander Björkman

**Comment by emilaalto** [comment]
I won't fix it for todays lesson, but I'll look into it. 👍

**Comment by emilaalto** [comment]
I think it's fixed now. :+1:
